logging:
  level:
    root: error
    me:
      sonam: info
info:
  app:
    name: Springboot me.sonam.account.Application
    description: This is a Springboot application
    version: 1.0.0

management:
  endpoint:
    health:
      show-details: always

server:
  port: 8080

aws:
  s3:
    region: https://sfo2.digitaloceanspaces.com
    accessKeyId: ${accessKeyId}
    secretAccessKey: ${secretAccessKey}
    bucket: sonam
    endpoint: ${endpoint}
    subdomain: ${subdomain}
    videoPath: videoapp/1/
    imageAclHeader: x-amz-acl
    imageAclValue: public-read
    presignDurationInMinutes: 60